# Generated by Django 6.0 on 2026-01-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_pushsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushSubscription',
        ),
    ]
