# Generated by Django 6.0 on 2026-01-11 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_delete_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_push', models.BooleanField(default=True)),
                ('enable_sound', models.BooleanField(default=True)),
                ('notify_on_mention', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='chat',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['sender', 'receiver', 'timestamp'], name='chat_chat_sender__29abd8_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['receiver', 'is_read', 'timestamp'], name='chat_chat_receive_bd26f1_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
