# Generated by Django 6.0 on 2026-01-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_notificationpreference_alter_chat_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='chat',
            name='chat_chat_sender__29abd8_idx',
        ),
        migrations.RemoveIndex(
            model_name='chat',
            name='chat_chat_receive_bd26f1_idx',
        ),
        migrations.DeleteModel(
            name='NotificationPreference',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='notification_sent',
        ),
    ]
