# Generated by Django 6.0 on 2026-01-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='products',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='services',
            field=models.TextField(null=True),
        ),
    ]
