# Generated by Django 6.0 on 2026-01-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_products_userprofile_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='products',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='services',
        ),
    ]
