# Generated by Django 6.0 on 2026-01-08 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='products',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='services',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='user.userprofile'),
        ),
    ]
