# Generated by Django 6.0 on 2026-01-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_business_products_remove_business_services_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_name',
            new_name='title',
        ),
    ]
