# Generated by Django 6.0 on 2026-01-10 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_business_name_business_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='user.userprofile'),
        ),
    ]
