# Generated by Django 6.0 on 2026-01-10 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_business_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='user.userprofile'),
        ),
    ]
